apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-test
  template:
    metadata:
      labels:
        app: web-test
    spec:
      containers:
        - name: htech7x
          image: httpd

